# Generated by Django 6.1 on 2026-08-31 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dias_validade_padrao', models.PositiveIntegerField(help_text='Validade média em dias após a colheita/recebimento')),
                ('armazem_recomendado', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('CAMARA_FRIA', 'Câmara Fria')], default='DEPOSITO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LoteEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('quantidade_inicial', models.DecimalField(decimal_places=2, help_text='Quantidade em Kg ou Caixas', max_digits=10)),
                ('quantidade_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('data_validade', models.DateField()),
                ('local_armazenado', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('CAMARA_FRIA', 'Câmara Fria')], max_length=20)),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.fruta')),
            ],
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_saida', models.DateTimeField(auto_now_add=True)),
                ('loja_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.loja')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saidas', to='estoque.loteentrada')),
                ('responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
