# Generated by Django 6.1 on 2026-09-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteentrada',
            name='codigo_lote',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
