# Generated by Django 6.1 on 2026-09-01 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_loteentrada_codigo_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(choices=[('TELEFONE', 'Telefone / WhatsApp'), ('IFOOD', 'iFood')], default='TELEFONE', max_length=10)),
                ('cliente_nome', models.CharField(max_length=150)),
                ('endereco_entrega', models.TextField()),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True)),
                ('valor_frutas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_PREPARO', 'Em Preparo'), ('SAIU_ENTREGA', 'Saiu para Entrega'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, help_text='Quantidade em Kg ou Unidades', max_digits=10)),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estoque.fruta')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.pedido')),
            ],
        ),
    ]
