# Generated by Django 6.1 on 2026-09-01 16:35

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_movimentacaoestoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='data_pedido',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='endereco_entrega',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='origem',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='telefone_contato',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_frete',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_frutas',
        ),
        migrations.AddField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço Unitário (R$)'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='canal_venda',
            field=models.CharField(choices=[('TELEFONE', '📞 Direto / Telefone / WhatsApp'), ('IFOOD', '🛵 iFood')], default='TELEFONE', max_length=20, verbose_name='Canal de Venda'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_ifood',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Pedido iFood (Opções)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_pedido',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_nome',
            field=models.CharField(max_length=150, verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADO', 'Confirmado / Em Separação'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='RASCUNHO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
