# Generated by Django 6.1 on 2026-09-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_remove_pedido_data_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo_pedido',
            field=models.CharField(default='PEDIDO-ANTIGO', editable=False, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
