# Generated by Django 6.1 on 2026-09-24 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_produto_alter_loteentrada_local_armazenado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loja',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='loteentrada',
            name='codigo_lote',
            field=models.CharField(default='LOTE-TEMP', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loteentrada',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='loteentrada',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loteentrada',
            name='fruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='estoque.fruta'),
        ),
        migrations.AlterField(
            model_name='loteentrada',
            name='quantidade_atual',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loteentrada',
            name='quantidade_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='canal_venda',
            field=models.CharField(choices=[('TELEFONE', '📞 Direto / Telefone / WhatsApp'), ('LOJA', '🏬 Solicitação de Loja'), ('IFOOD', '🛵 iFood')], default='LOJA', max_length=20, verbose_name='Canal de Venda'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente_nome',
            field=models.CharField(max_length=150, verbose_name='Nome do Solicitante / Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('CONFIRMADO', 'Confirmado / Em Separação'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='CONFIRMADO', max_length=20),
        ),
    ]
