# Generated by Django 6.1 on 2026-09-24 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_alter_loja_endereco_alter_loteentrada_codigo_lote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_criacao']},
        ),
        migrations.AddField(
            model_name='pedido',
            name='loja_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='estoque.loja', verbose_name='Loja Solicitante'),
        ),
    ]
