# Generated by Django 6.1 on 2026-09-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_alter_pedido_options_pedido_loja_solicitante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteentrada',
            name='codigo_lote',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
