# Generated by Django 6.1 on 2026-09-30 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_loteentrada_codigo_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraCeasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto_digitado', models.CharField(blank=True, max_length=100, null=True)),
                ('quantidade_comprada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Comprada')),
                ('preco_custo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Custo (R$)')),
                ('preco_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda (R$)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Conferência'), ('CONFERIDO', 'Conferido e Entrada no Estoque'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compras_ceasa', to='estoque.fruta')),
                ('lojas_destinatarias', models.ManyToManyField(to='estoque.loja', verbose_name='Lojas Disponibilizadas')),
                ('responsavel_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
