# Generated by Django 6.1 on 2026-09-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_compraceasa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compraceasa',
            name='preco_venda',
        ),
        migrations.AddField(
            model_name='compraceasa',
            name='preco_venda_banca',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Venda (Banca / Kg / Dúzia)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compraceasa',
            name='preco_venda_caixa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Venda (Caixa Fechada)'),
            preserve_default=False,
        ),
    ]
