# Generated by Django 6.1 on 2026-09-30 16:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_remove_compraceasa_preco_venda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loteentrada',
            name='lojas_destinatarias',
            field=models.ManyToManyField(blank=True, to='estoque.loja', verbose_name='Lojas Autorizadas'),
        ),
        migrations.AddField(
            model_name='loteentrada',
            name='preco_custo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço de Custo (R$)'),
        ),
        migrations.AddField(
            model_name='loteentrada',
            name='preco_venda_banca',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço Venda (Banca)'),
        ),
        migrations.AddField(
            model_name='loteentrada',
            name='preco_venda_caixa',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço Venda (Caixa)'),
        ),
    ]
