# Generated by Django 6.1 on 2026-09-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_loteentrada_lojas_destinatarias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruta',
            name='categoria',
            field=models.CharField(choices=[('FRUTA', 'Frutas'), ('LEGUME', 'Legumes'), ('VERDURA', 'Verduras'), ('OUTRO', 'Outros / Insumos')], default='FRUTA', max_length=20, verbose_name='Categoria do Produto'),
        ),
    ]
